services:
  app:
    image: ghcr.io/bappeda-dev-team/edokin:latest
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:8.0.39
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASS
      - MYSQL_DATABASE=$DB_DATABASE
    restart: on-failure
    volumes:
      - edokin-database-volume:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d

volumes:
  edokin-database-volume: {}
